version: '3.9'
services:
    db:
        container_name: db
        image: mysql:8.0.22
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony

    php:
        container_name: php-fpm
        build:
            context: ./php-fpm
            args:
                ENABLE_PHP_XDEBUG: 0
        ports:
            - "9000:9001"
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
        depends_on: 
            - db

    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - "80:80"
        depends_on: 
            - php
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./symfony:/var/www/symfony:cached

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
